from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Table, TableStyle, Spacer
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime

def generate_report(
    filename,
    career,
    match_score,
    predicted_role,
    detected_skills,
    missing_skills,
    salary,
    growth
):

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(filename)

    story = []

    story.append(Paragraph(
    "<font size=22><b>Career Analysis Report</b></font>",
    styles["Title"]
))

    story.append(Paragraph(
    "Future Workforce Evolution Engine",
    styles["Heading2"]
))

    story.append(
    Paragraph(
        f"Generated on : {datetime.now().strftime('%d-%m-%Y %H:%M')}",
        styles["BodyText"]
    )
)

    story.append(Spacer(1, 0.3 * inch))


    # story.append(Paragraph("<b>Future Workforce Evolution Engine</b>", styles["Title"]))

    # story.append(Paragraph(f"<b>Recommended Career:</b> {career}", styles["BodyText"]))

    # story.append(Paragraph(f"<b>Match Score:</b> {match_score:.2f}%", styles["BodyText"]))

    # story.append(Paragraph(f"<b>ML Prediction:</b> {predicted_role}", styles["BodyText"]))

    # story.append(Paragraph(f"<b>Detected Skills:</b> {', '.join(detected_skills)}", styles["BodyText"]))

    # story.append(Paragraph(f"<b>Missing Skills:</b> {', '.join(missing_skills)}", styles["BodyText"]))

    # story.append(Paragraph(f"<b>Average Salary:</b> {salary}", styles["BodyText"]))

    # story.append(Paragraph(f"<b>Growth Score:</b> {growth}", styles["BodyText"]))

    table_data = [
        ["Field", "Value"],
        ["Recommended Career", career],
        ["Match Score", f"{match_score:.2f}%"],
        ["AI Prediction", predicted_role],
        ["Detected Skills", ", ".join(detected_skills)],
        ["Missing Skills", ", ".join(missing_skills)],
        ["Average Salary", str(salary)],
        ["Growth Score", str(growth)],
    ]

    table = Table(table_data, colWidths=[2.2 * inch, 4.2 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
]))

    story.append(table) 


    story.append(Spacer(1, 0.2 * inch))

    if match_score >= 80:
         assessment = "Excellent Match ✅"

    elif match_score >= 60:
         assessment = "Good Match"

    elif match_score >= 40:
         assessment = "Moderate Match ⚠"
    
    else:
         assessment = "Needs Improvement ❌"

    recommendation = (
        f"Your profile is currently a {match_score:.2f}% match for the role of "
        f"{career}. Focus on developing the following skills: "
        f"{', '.join(missing_skills)}. "
    "Improving these skills can significantly increase your employability."
)

    story.append(
        Paragraph(
        f"<b>Overall Assessment:</b> {assessment}",
        styles["Heading2"]
    )
)

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
        "<b>Recommendation</b>",
        styles["Heading2"]
    )
)
    
    

    story.append(
        Paragraph(
        recommendation,
        styles["BodyText"]
    )
)
    
    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
        "<font size=9 color='grey'>Generated by Future Workforce Evolution Engine</font>",
        styles["BodyText"]
    )
)
    
    doc.build(story)